#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. >/dev/null 2>&1 && pwd )"
if [ -r $PDIR/share/lib/unbound/unbound-1.0.0-exec.jar ]; then
  java -jar $PDIR/share/lib/unbound/unbound-1.0.0-exec.jar $@
elif [ -r $DIR/target/unbound-1.0.0-exec.jar ]; then
  # for testing in dev environments
  java -jar $DIR/target/unbound-1.0.0-exec.jar $@
else
  # for other environments
  java -jar $DIR/unbound-1.0.0-exec.jar $@
fi

if [[ "$*" == *--generate-hocon* ]] || [[ "$*" == *--generate-json* ]] 
then
  echo "Done"
else
  mvn $@
fi
